# Docker Compose File Not Working Correctly Because Of Some Volume Issues :(
# Version of Docker-compose
version: '3.8'
services:
  # Service name
  inventory-frontend:
    image: inventory-frontend
    stdin_open: true
    ports:
        # External port:Internal port
      - 3000:3000
    networks:
      - inventory-app

  # Service name
  inventory-backend:
    image: inventory-backend
    stdin_open: true
    ports:
        # External port:Internal port
      - 5000:5000
    networks:
      - inventory-app


networks:
  inventory-app:
    driver: bridge