# Docker Compose File Not Working Correctly Because Of Some Volume Issues :(
# Version of Docker-compose
version: '3.8'
services:
  # Service name
  node:
    # Creating a custom image
    build:
      # Location to the Dockerfile
      context: .
      # Name of the Dockerfile
      dockerfile: Dockerfile
    volumes:
          - ./nodeVolume:/
    ports:
        # External port:Internal port
      - 5000:5000
  # Service name
  react:
    # Creating a custom image
    build:
      # Location to the Dockerfile
      context: "./client"
      # Name of the Dockerfile
      dockerfile: Dockerfile
    volumes:
        - ./reactVolume :/client
    ports:
        # External port:Internal port
      - 3000:3000
volumes:
  # Declaring the node service volume.
  nodeVolume:
  reactVolume: